jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: dbt_postgres
      password: dbt_postgres_pass
      port: 5432
      dbname: dbt_db
      schema: public
      threads: 4