models: 
  - name: customers_stg 
    columns: 
      - name: Email 
        tests: 
          - string_not_empty

  - name: orders_stg 
    columns: 
      - name: OrderID 
        tests: 
          - unique 
          - not_null 

      - name: StatusCD 
        description: "{{ doc('StatusCD') }}"
        tests: 
          - accepted_values: 
              values: ["Shipped","Pending","Delivered","Processing","Cancelled"] 

  - name: orderitems_stg 
    columns: 
      - name: OrderID 
        tests: 
          - relationships: 
              to: ref('orders_stg') 
              field: OrderID 
  - name: orderitems_uniq 
    tests: 
      - dbt_expectations.expect_table_row_count_to_equal_other_table: 
          compare_model: ref("orders_stg")
  
